'use client';
import Image from 'next/image';
import Link from 'next/link';
import { useState } from 'react';
import { Bot, Send, Sparkles, User } from 'lucide-react';
import { Header } from '@/components/Header';
import { useSelectedDish } from '@/context/SelectedDishContext';

type Message={role:'user'|'assistant';content:string;alternative?:string};
const quick=['Is this healthy?','Is it high in protein?','Does it have allergens?','Is it good for weight loss?','Suggest healthier alternative?'];
export default function AssistantPage(){
  const {selectedDish}=useSelectedDish(); const [messages,setMessages]=useState<Message[]>([]); const [input,setInput]=useState(''); const [loading,setLoading]=useState(false);
  async function send(question?:string){ const q=(question??input).trim(); if(!q||!selectedDish||loading)return; const history=[...messages]; setMessages(p=>[...p,{role:'user',content:q}]); setInput(''); setLoading(true); try { const res=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({dish:selectedDish,question:q,history})}); const data=await res.json(); setMessages(p=>[...p,{role:'assistant',content:data.answer,alternative:data.suggestedAlternative}]); } catch { setMessages(p=>[...p,{role:'assistant',content:"I'm having trouble right now. Please try again."}]); } finally { setLoading(false); } }
  return <main className="min-h-screen"><Header/><div className="mx-auto max-w-5xl px-4 py-12 sm:px-6">{!selectedDish?<div className="rounded-3xl bg-white p-12 text-center shadow-soft"><Sparkles className="mx-auto text-orange-600" size={42}/><h1 className="mt-5 text-3xl font-black">Select a dish from menu first</h1><p className="mt-3 text-gray-500">Open any dish and choose “Ask About This Dish” to start a nutrition conversation.</p><Link href="/#menu" className="mt-7 inline-block rounded-full bg-orange-600 px-6 py-3 font-bold text-white hover:bg-orange-700">Back to Menu</Link></div>:<>
      <section className="overflow-hidden rounded-3xl bg-white shadow-soft"><div className="grid md:grid-cols-[240px_1fr]"><div className="relative h-56 md:h-full"><Image src={selectedDish.image} alt={selectedDish.name} fill className="object-cover"/></div><div className="p-6 sm:p-8"><span className="rounded-full bg-orange-100 px-3 py-1 text-sm font-bold text-orange-700">Selected dish</span><h1 className="mt-4 text-3xl font-black">{selectedDish.name}</h1><p className="mt-2 text-gray-600">{selectedDish.description}</p><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{[['Calories',selectedDish.nutrition.calories],['Protein',selectedDish.nutrition.protein],['Carbs',selectedDish.nutrition.carbs],['Fats',selectedDish.nutrition.fats]].map(([a,b])=><div key={a} className="rounded-2xl bg-amber-50 p-3"><p className="text-xs font-bold text-gray-500">{a}</p><p className="text-lg font-black">{b}</p></div>)}</div></div></div></section>
      <section className="mt-8 rounded-3xl bg-white p-5 shadow-soft sm:p-8"><div className="flex items-center gap-3 border-b border-gray-100 pb-5"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-orange-600 text-white"><Bot/></div><div><h2 className="font-black">FlavorHub AI Assistant</h2><p className="text-sm text-gray-500">Friendly dish-specific nutrition guidance</p></div></div>
        <div className="mt-5 min-h-[320px] space-y-4 rounded-2xl bg-amber-50/60 p-4 sm:p-6">{messages.length===0&&<div className="grid min-h-[270px] place-items-center text-center text-gray-500"><div><Sparkles className="mx-auto mb-3 text-orange-500"/><p className="font-semibold">Ask anything about ingredients, calories, protein, allergens or healthier choices.</p></div></div>}{messages.map((m,i)=><div key={i} className={`flex gap-3 ${m.role==='user'?'justify-end':''}`}>{m.role==='assistant'&&<div className="mt-1 grid h-8 w-8 shrink-0 place-items-center rounded-full bg-orange-600 text-white"><Bot size={16}/></div>}<div className={`max-w-[82%] rounded-2xl px-4 py-3 leading-7 ${m.role==='user'?'bg-gray-900 text-white':'border border-orange-100 bg-white text-gray-700 shadow-sm'}`}>{m.content.split('\n').map((line,j)=><p key={j}>{line}</p>)}{m.alternative&&<div className="mt-3 rounded-xl bg-green-50 p-3 text-sm font-bold text-green-800">Suggested alternative: {m.alternative}</div>}</div>{m.role==='user'&&<div className="mt-1 grid h-8 w-8 shrink-0 place-items-center rounded-full bg-gray-900 text-white"><User size={16}/></div>}</div>)}{loading&&<div className="space-y-2 rounded-2xl border border-orange-100 bg-white p-4 text-sm font-semibold text-gray-600 shadow-sm"><p className="loader-step">1. Reading dish ingredients...</p><p className="loader-step">2. Checking nutrition facts...</p><p className="loader-step">3. Generating personalized advice...</p></div>}</div>
        <div className="mt-5 flex flex-wrap gap-2">{quick.map(q=><button key={q} disabled={loading} onClick={()=>send(q)} className="rounded-full border border-orange-200 bg-orange-50 px-3 py-2 text-sm font-bold text-orange-700 hover:bg-orange-100 disabled:opacity-50">{q}</button>)}</div>
        <div className="mt-5 flex gap-3"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')send();}} placeholder="Ask about this dish..." className="min-w-0 flex-1 rounded-full border border-gray-200 px-5 py-3 outline-none focus:border-orange-500"/><button onClick={()=>send()} disabled={loading||!input.trim()} className="grid h-12 w-12 shrink-0 place-items-center rounded-full bg-orange-600 text-white hover:bg-orange-700 disabled:opacity-50" aria-label="Send"><Send size={20}/></button></div>
      </section></>}</div></main>;
}
